apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  # Add finalizer to ensure that Helm release is deleted before the app
  finalizers:
    - argocd.argoproj.io/resources-finalizer # Use domain-qualified finalizer
spec:
  project: default
  source:
    # Source is the Git repository containing this Application manifest and the wrapper chart
    repoURL: https://github.com/gergelysotidm/eu-data-platform.git
    path: argo/apps/100-traefik # Path to the wrapper chart directory within the Git repo
    targetRevision: HEAD # Or your specific branch/tag

    # Helm configuration for the wrapper chart
    helm:
      # releaseName is optional here, defaults based on app name
      releaseName: traefik
      # Values file is implicitly values.yaml within the source path
      # valueFiles: # Not needed if using default values.yaml
      #  - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik # Deploy Traefik into its own namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Ensure the traefik namespace is created
