# Default values for zitadel.
zitadel:
  zitadel:
    masterkey: x123456789012345678901234567891y
    configmapConfig:
      ExternalSecure: true
      ExternalDomain: zitadel.ovh.playground.dataminded.cloud
      TLS:
        Enabled: false
      FirstInstance:
        Org:
          Human:
            Username: "admin"
            Password: "SecureP@ssw0rd!"
            FirstName: "Default"
            LastName: "Admin"
            Email:
              Address: "admin@dataminded.com"
              Verified: true
    configSecretName: zitadel-credentials
    configSecretKey: config.yaml
#    dbSslCaCrtSecret: pg-certificate
  ingress:
    enabled: true
    className: traefik
    annotations:
      # Enable TLS with Let's Encrypt
      traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/service.serversscheme: "h2c"
    hosts: 
      - host: zitadel.ovh.playground.dataminded.cloud
        paths:
          - path: /
            pathType: Prefix

